### ISSUE TITLE
求个联系方式

### ISSUE THREAD

**Issue by photkey** [jingyuexing/bilibiliAPI#5]
希望增加多一些api接口，如果可以的话 希望留个联系方式，聊下可否付费定制。如果这里不方便回复的话，可以发我邮箱：vimcode@qq.com

**Comment by jingyuexing** [comment]
有其它接口需求可以说一下 提一个新的issue 我只是单纯的享受开源的快乐 而非是考虑到金钱 如果打赏的话 也是可以的,但是我可能只会接收加密货币的打赏 其他的方式可能会泄漏个人信息
